const defaultPlan = [
  { day: '周一', short: '一', title: '上肢推力', time: '06:30', duration: '50 分钟', done: true, exercises: [['杠铃卧推','4 组 × 8 次','胸部'],['哑铃肩推','3 组 × 10 次','肩部'],['绳索下压','3 组 × 12 次','手臂'],['平板支撑','3 组 × 45 秒','核心']] },
  { day: '周二', short: '二', title: '下肢力量 & 核心', time: '06:30', duration: '55 分钟', done: false, exercises: [['深蹲','4 组 × 6 次','腿部'],['罗马尼亚硬拉','3 组 × 8 次','腿后侧'],['保加利亚分腿蹲','3 组 × 10 次','臀腿'],['悬垂举腿','3 组 × 12 次','核心']] },
  { day: '周三', short: '三', title: '主动恢复', time: '19:00', duration: '30 分钟', done: false, exercises: [['轻松骑行','20 分钟','有氧'],['髋部流动','10 分钟','拉伸']] },
  { day: '周四', short: '四', title: '上肢拉力', time: '06:30', duration: '50 分钟', done: false, exercises: [['引体向上','4 组 × 6 次','背部'],['杠铃划船','3 组 × 8 次','背部'],['面拉','3 组 × 12 次','肩部'],['哑铃弯举','3 组 × 10 次','手臂']] },
  { day: '周五', short: '五', title: '全身代谢', time: '07:00', duration: '45 分钟', done: false, exercises: [['壶铃摆动','4 组 × 15 次','全身'],['波比跳','3 组 × 10 次','心肺'],['农夫走','3 组 × 40 米','核心']] },
  { day: '周六', short: '六', title: '自由活动', time: '09:00', duration: '30 分钟', done: false, exercises: [['户外散步','30 分钟','恢复']] },
  { day: '周日', short: '日', title: '休息', time: '--:--', duration: '完全休息', done: false, exercises: [] }
];
let plan = JSON.parse(localStorage.getItem('vanta-plan') || 'null') || defaultPlan;
let selectedDay = new Date().getDay() === 0 ? 6 : new Date().getDay() - 1;
let editingToday = false;
let draftToday = null;
const $ = s => document.querySelector(s); const $$ = s => [...document.querySelectorAll(s)];
function pad(n){return String(n).padStart(2,'0')}
function escapeHTML(value){return String(value ?? '').replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function persistPlan(){localStorage.setItem('vanta-plan',JSON.stringify(plan))}
function updateClock(){const d=new Date();const date=`${d.getFullYear()}.${pad(d.getMonth()+1)}.${pad(d.getDate())}`;const time=`${pad(d.getHours())}:${pad(d.getMinutes())}`;$('#heroDate').textContent=date;$('#heroTime').textContent=time;$('#detailDate').textContent=`${d.getFullYear()}年${pad(d.getMonth()+1)}月${pad(d.getDate())}日`;$('#detailTime').textContent=time;$('#todayLabel').textContent=`今日 · ${plan[selectedDay].day}`}
function sessionSummary(p){if(!p.exercises.length)return '恢复活动 · 放松与拉伸';const names=p.exercises.slice(0,3).map(e=>e[0]);const extra=p.exercises.length>3?' · 核心':'';return `${names.join(' · ')}${extra}`}
function renderHome(){const p=plan[selectedDay];$('#todayTitle').textContent=p.title;$('#todayMeta').textContent=sessionSummary(p);const strip=$('#homeWeekStrip');strip.innerHTML=plan.map((x,i)=>`<button class="week-day ${i===selectedDay?'current ':''}${x.done?'done ':''}${x.title==='休息'?'rest':''}" data-day="${i}"><span class="day-name">${x.short}</span><span class="day-num">${i+1}</span><i class="day-state"></i></button>`).join('');$$('.week-day').forEach(b=>b.onclick=()=>{selectedDay=+b.dataset.day;renderHome();renderToday();updateClock()});const completed=plan.filter(x=>x.done&&x.title!=='休息');const count=completed.length;$('#completedCount').innerHTML=`${count} <small>/ 5</small>`;$('#progressBar').style.width=`${Math.min(100,count/5*100)}%`;$('#trainedSessions').innerHTML=completed.length?completed.map(x=>`<div class="trained-session"><b>${x.day}</b><span>${x.title}</span></div>`).join(''):'<div class="trained-empty">还没有完成的训练</div>';const parts=[...new Set(completed.flatMap(x=>x.exercises.map(e=>e[2])))];$('#trainedParts').textContent=parts.length?`部位 · ${parts.join(' / ')}`:'完成训练后显示身体部位'}
function renderToday(){const p=plan[selectedDay];$('#detailHeading').textContent=selectedDay===((new Date().getDay()+6)%7)?'今日训练':`${p.day}训练`;$('#detailTitleWrap').innerHTML=editingToday?`<label class="banner-title-field"><span>训练标题</span><input id="detailTitleInput" data-field="title" value="${escapeHTML(draftToday.title)}" aria-label="训练标题" /></label>`:`<h2 id="detailTitle">${escapeHTML(p.title)}</h2>`;$('#detailSubtitle').textContent=`${p.title==='休息'?'恢复身心': '专注动作质量与稳定性'} · ${p.duration}`;$('#detailNumber').textContent=pad(selectedDay+1);$('#editTodayBtn').textContent=editingToday?'取消编辑':'编辑今日计划';$('#daySelector').innerHTML=plan.map((x,i)=>`<button class="day-select ${i===selectedDay?'active':''}" data-day="${i}">${x.short}</button>`).join('');$$('.day-select').forEach(b=>b.onclick=()=>{editingToday=false;draftToday=null;selectedDay=+b.dataset.day;renderToday();renderHome();updateClock()});$('#exerciseList').innerHTML=p.exercises.length?p.exercises.map((e,i)=>`<div class="exercise-row"><span class="exercise-index">${pad(i+1)}</span><div><div class="exercise-name">${escapeHTML(e[0])}</div><div class="exercise-detail">${escapeHTML(e[1])}</div></div><span class="exercise-tag">${escapeHTML(e[2])}</span></div>`).join(''):`<div class="empty-state">今天是休息日。让身体恢复，为下一次训练蓄力。</div>`;const btn=$('#completeBtn');btn.classList.toggle('done',p.done);$('#completeText').textContent=p.done?'今日已完成':'标记今日完成';$('#exerciseList').hidden=editingToday;btn.hidden=editingToday;$('#todayEditor').hidden=!editingToday;if(editingToday)renderTodayEditor()}
function renderTodayEditor(){const editor=$('#todayEditor');if(!draftToday)return;const rows=draftToday.exercises.map((e,i)=>`<div class="editor-row" data-index="${i}"><div class="editor-row-top"><span class="editor-index">${pad(i+1)}</span><div class="editor-move"><button type="button" class="editor-icon" data-action="up" aria-label="上移" title="上移">↑</button><button type="button" class="editor-icon" data-action="down" aria-label="下移" title="下移">↓</button></div><button type="button" class="editor-icon editor-delete" data-action="remove" aria-label="删除" title="删除">×</button></div><label class="editor-field"><span>动作名称</span><input data-field="name" data-index="${i}" value="${escapeHTML(e[0])}" /></label><div class="editor-pair"><label class="editor-field"><span>组数 / 次数</span><input data-field="detail" data-index="${i}" value="${escapeHTML(e[1])}" /></label><label class="editor-field"><span>训练部位</span><input data-field="part" data-index="${i}" value="${escapeHTML(e[2])}" /></label></div></div>`).join('');editor.innerHTML=`<div class="editor-shell"><div class="editor-heading"><div><p class="editor-kicker">EDIT SESSION</p><h3>调整训练动作</h3></div><span class="editor-count">${draftToday.exercises.length} 项</span></div><div class="editor-list">${rows||'<div class="editor-empty">添加第一个训练项目</div>'}</div><button class="add-exercise" id="addExerciseBtn" type="button"><span>＋</span>新增训练项目</button><div class="editor-footer"><button class="secondary-button" id="cancelTodayBtn" type="button">取消</button><button class="primary-button editor-save" id="saveTodayBtn" type="button">保存更改</button></div></div>`}
function startTodayEdit(){const p=plan[selectedDay];draftToday={title:p.title,time:p.time,duration:p.duration,done:p.done,day:p.day,short:p.short,exercises:p.exercises.map(e=>[...e])};editingToday=true;renderToday()}
function cancelTodayEdit(){editingToday=false;draftToday=null;renderToday()}
function saveTodayEdit(){if(!draftToday)return;draftToday.title=draftToday.title.trim()||'休息';draftToday.exercises=draftToday.exercises.map(e=>[e[0].trim()||'未命名动作',e[1].trim()||'按需完成',e[2].trim()||'全身']);plan[selectedDay]=draftToday;persistPlan();editingToday=false;draftToday=null;renderHome();renderToday();showToast('今日计划已保存')}
function showToast(message){$('#toast').textContent=message;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1500)}
function handleTodayEditorClick(event){const button=event.target.closest('button[data-action]');if(!button||!draftToday)return;const row=button.closest('.editor-row');const index=Number(row.dataset.index);if(button.dataset.action==='remove'){draftToday.exercises.splice(index,1)}if(button.dataset.action==='up'&&index>0){[draftToday.exercises[index-1],draftToday.exercises[index]]=[draftToday.exercises[index],draftToday.exercises[index-1]]}if(button.dataset.action==='down'&&index<draftToday.exercises.length-1){[draftToday.exercises[index+1],draftToday.exercises[index]]=[draftToday.exercises[index],draftToday.exercises[index+1]]}renderTodayEditor()}
function handleTodayEditorInput(event){if(!draftToday||!event.target.dataset.field)return;const field=event.target.dataset.field;if(field==='title')draftToday.title=event.target.value;else{const i=Number(event.target.dataset.index);const key={name:0,detail:1,part:2}[field];draftToday.exercises[i][key]=event.target.value}}
function renderEditor(){const ed=$('#planEditor');ed.innerHTML=plan.map((p,i)=>`<div class="plan-row"><span class="plan-day">${p.day}</span><input class="plan-input" data-field="title" data-day="${i}" value="${escapeHTML(p.title)}" aria-label="${p.day}训练内容" /></div>`).join('');$$('.plan-input').forEach(input=>input.oninput=()=>{const i=+input.dataset.day;plan[i].title=input.value||'休息';persistPlan();renderHome();renderToday()})}
function showView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`${name}View`));$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.nav===name));if(name==='today')renderToday();if(name==='week')renderEditor();window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-nav]').forEach(b=>b.onclick=()=>showView(b.dataset.nav));$('#openTodayFromHome').onclick=()=>showView('today');$('#editTodayBtn').onclick=()=>editingToday?cancelTodayEdit():startTodayEdit();$('#detailTitleWrap').addEventListener('input',handleTodayEditorInput);$('#todayEditor').addEventListener('click',handleTodayEditorClick);$('#todayEditor').addEventListener('input',handleTodayEditorInput);$('#todayEditor').addEventListener('click',event=>{if(event.target.id==='addExerciseBtn'){draftToday.exercises.push(['新训练动作','3 组 × 10 次','全身']);renderTodayEditor()}if(event.target.id==='cancelTodayBtn')cancelTodayEdit();if(event.target.id==='saveTodayBtn')saveTodayEdit()});$('#completeBtn').onclick=()=>{plan[selectedDay].done=!plan[selectedDay].done;persistPlan();renderHome();renderToday();showToast(plan[selectedDay].done?'今日训练已完成':'已取消完成');};$('#savePlanBtn').onclick=()=>showToast('周计划已保存');$('#settingsBtn').onclick=()=>showToast('计划已自动保存在本机');
renderHome();renderToday();updateClock();setInterval(updateClock,1000);
